version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: rpa_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: rpa_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
    - API_URL=http://api:8000
    - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
    volumes:
      - .:/app