FROM python:3.11-slim

# instalar chromium
RUN apt-get update && apt-get install -y \
    chromium \
    chromium-driver \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN pip install -r requirements-api.txt

ENV CHROME_BIN=/usr/bin/chromium

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "10000"]